apiVersion: v1
kind: Service
metadata:
  name: fastfood-api
  labels:
    app: fastfood-api
    tier: backend
spec:
  type: NodePort
  selector:
    app: fastfood-api
    tier: backend
  ports:
  - protocol: TCP
    port: 3000 # Service port (exposed to the app)
    targetPort: 3000 # Container port (API port inside the pod)
    nodePort: 30163
