apiVersion: v1
kind: Service
metadata:
  name: fastfood-api
  labels:
    app: fastfood-api
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: fastfood-api
    tier: backend
  ports:
  - name: http
    protocol: TCP
    port: 80 # Service port (exposed to the app)
    targetPort: 3000 # Container port (API port inside the pod)
